import {
  BarChart2,
  User,
  Layers,
  Briefcase,
  GraduationCap,
  Settings,
  MessageCircle,
  FileText,
  LogOut,
  Star,
  Wrench,
  Globe,
} from "lucide-react";
export const sidebarItem = [
  {
    name: "Overview",
    icon: BarChart2,
    color: "#6366f1",
    href: "/admin/dashboard",
  },
  {
    name: "About Me",
    icon: User,
    color: "#10b981",
    href: "/admin/about",
  },
  {
    name: "Skills",
    icon: Wrench,
    color: "#f59e0b",
    href: "/admin/skills",
  },
  {
    name: "Projects",
    icon: Layers,
    color: "#3b82f6",
    href: "/admin/projects",
  },
  {
    name: "Experience",
    icon: Briefcase,
    color: "#8b5cf6",
    href: "/admin/experiences",
  },
  {
    name: "Education",
    icon: GraduationCap,
    color: "#ec4899",
    href: "/admin/educations",
  },
  {
    name: "Services",
    icon: Globe,
    color: "#06b6d4",
    href: "/admin/services",
  },
  {
    name: "Testimonials",
    icon: Star,
    color: "#facc15",
    href: "/admin/testimonials",
  },
  {
    name: "Blog",
    icon: FileText,
    color: "#14b8a6",
    href: "/admin/blogs",
  },
  {
    name: "Messages",
    icon: MessageCircle,
    color: "#f97316",
    href: "/admin/messages",
  },
  {
    name: "Settings",
    icon: Settings,
    color: "#64748b",
    href: "/admin/settings",
  },
  {
    name: "Logout",
    icon: LogOut,
    color: "#ef4444",
    href: "/admin/logout",
  },
];
